### ISSUE TITLE
Ignore null fields options

### ISSUE THREAD

**Issue by MikeShiner** [epoberezkin/fast-deep-equal#42]
I would love to see options object passed in with a ignoreIfNull attribute. I am constantly comparing objects which sometimes have their field initialised with null, but I only want to deep equals on the fields that have values.

**Comment by Merri** [comment]
I made a quick test. Adding options object and then checking for the suggested condition reduces ops/sec by roughly 5 % (of ES6 version) and by roughly 10 % when passing `{ ignoreIfNull: true }`.

```js
  if (a === b) return true
  // added this line; also, passed options to each equal() call of course
  if (options.ignoreIfNull && a == null && b == null) return true
  // this change does not make object with key but undefined value to equal with missing key
```

To me this means it would make more sense to expose a new method with the extra condition instead of adding an options object. Something like `fast-deep-equal/es6-null' or whatever the name should be.

Also, if missing key should equal with key with undefined value, and null should also be equivalent, well, you get a lot more complexity that will probably slow things down even more, because comparison between `Object.keys().length` can no longer be used to quickly detect difference between two objects.

If performance matters then you should probably refactor the fields so that they always match. Either always have the keys there with `null`, or remove the `null` values.

**Comment by epoberezkin** [comment]
Application may need to treat absent, undefined and null properties as equivalent for the application purposes, but it’s incorrect to say they are equal.

So the possible solution is to traverse both objects (in the application code) and remove null and undefined properties before passing the objects to this library for deep equality test.

The alternative solution could be to fork this library, rename it to “fast-deep-equivalent” (or anything that makes sense) and change the comparison.

Closing as out of scope.
