### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by epoberezkin** [epoberezkin/fast-deep-equal#6]
Should `equal(NaN, NaN)` return `true`?

**Comment by Ygg01** [comment]
No. `NaN` means value you get is undefined. Take for example following value `x*1/x` It's obvious this value is 1 whatever X is, however look what happens when x approaches really small value (e.g. `1e-324*(1/1e-324)`) the value becomes `NaN`.

Another example could be `0*x`. The value is obviously 0 for any `x != 0` so when e.g. `x` is `1e+324*(1/1e+324)` it becomes `NaN` as well.

We can prove first `NaN` = 1 and that second `NaN`  = 0. If `NaN == NaN` then we can prove ` 1==0`.

**Comment by langpavel** [comment]
But for purpose of this library?

**Comment by epoberezkin** [comment]
> We can prove first NaN = 1 and that second NaN = 0. If NaN == NaN then we can prove 1==0.

This proof has (or would have) an obvious logical flaw, like all sophisms, discussing which is out of scope here.

I think the right approach is just do what most other libraries do (still need to check it).

**Comment by langpavel** [comment]
Ok, I just want clear contract from this library.
Statement that `NaN`s are treated as nonequals is fine.
*BUT*:
```js
Object.is(NaN,NaN) // → true
```
BTW thank you for spending/wasting time on this :+1:

**Comment by Ygg01** [comment]
> This proof has (or would have) an obvious logical flaw, like all sophisms, discussing which is out of scope here.

It's not a sophism and doesn't contain a logical flaw. It's essentially the mathematical explanation of why [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754-1985) has that NaN is not equal NaN.

**Comment by langpavel** [comment]
Ok, @Ygg01 and @epoberezkin, all I'm hunting for is *contract* or *declaration*. Nothing more. `Object.is` is standart now, so I'm expecting that if I declare two structures or when I shallow copy one structure to second one, they will be considered equal because you cannot derive different result by passing it through pure function:
```js
> Object.is({a:1}, {a:1})
false
> const notNumber = parseInt()
undefined
> notNumber
NaN
> notNumber === notNumber
false
> Object.is(notNumber, notNumber)
true
> Object.is(notNumber, NaN)
true
```

**Comment by langpavel** [comment]
from the point, there is no way to decide between two `NaN` values, so they can be **safely considered equal for purpose of this library**.

**Comment by langpavel** [comment]
One line path is to replace [line 8](https://github.com/epoberezkin/fast-deep-equal/blob/master/index.js#L8):
```js
  if (a === b) return true;
```
with this:
```js
  if (Object.is(a, b)) return true;
```

**Comment by langpavel** [comment]
easy-peasy :+1:

**Comment by Ygg01** [comment]
@langpavel I am unsure. I think comparing `NaN` is still a bizarre thing. But maybe in this case it makes sense.

Also, you could just use a `Object.is` polyfills:
```js
    if (x === y) { // Ref check
      // check for +0 != -0
      return x !== 0 || 1 / x === 1 / y;
    } else {
      // check NaN == NaN
      return x !== x && y !== y;
    }
```

**Comment by langpavel** [comment]
@Ygg01 Yeah, you can see that Javascript itself threats `NaN` to be same as other `NaN`,
and thanks for positive and negative zero…

> But maybe in this case it makes sense

Yes, definitely :100:

**Comment by Ygg01** [comment]
@langpavel 
> Yeah, you can see that modern Javascript itself threats NaN to be same as other NaN,

Sure, but ***modern*** JavaScript is in this respect an outlier. No other language (that I am aware) does this and in JS both `NaN === NaN` and `NaN == NaN` are false.

**Comment by langpavel** [comment]
Related: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness
See also discussion in #18
